[workspace]
types = "tests/"

[features]
seeds = false
skip-lint = false

[programs.localnet]
typescript_fetch = "8tKNmp7w19TCH9cvg7qTXR3etBqnofHgkTMT2ybxJ7Xx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/chalda/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
