[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_runtime_limitations = "6rtKQYnusfX9bXu4c5x26j6JkTefJmHExhpc5oEHCgj7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/chalda/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
