[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_tx_cost = "BbkLEpNuXhFv1fTeRq6qJpm8BK1aecGWb2g8iqmvNYiw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
